/**
 * hook-flags.mjs — Profile resolver (registry-derived, internal-rule Single SSOT)
 *
 * Profile membership is derived from the `profile` field of hook-registry.mjs entries.
 * This file is not the SSOT.
 *
 * Changing profiles:
 *   ❌ Do not edit this file
 *   ✅ Modify `profile` field in hook-registry.mjs entry + run regen-hooks-settings.mjs
 *
 * Environment variables:
 *   ECC_HOOK_PROFILE   = minimal | standard (default: standard)
 *   ECC_DISABLED_HOOKS = Comma-separated hookId list (forced disabling)
 *
 * @see .cli/lib/hook-registry.mjs (Single SSOT)
 * @see .claude/rules/common/hooks.md 
 */
import { flattenRegistry } from './hook-registry.mjs';

const VALID_PROFILES = new Set(['minimal', 'standard']);

let _profileMapCache = null;

function buildProfileMap() {
  if (_profileMapCache) return _profileMapCache;
  const flat = flattenRegistry();
  const minimalIds = new Set();
  const standardIds = new Set();
  for (const h of flat) {
    if (h.profile === 'minimal') minimalIds.add(h.id);
    else if (h.profile === 'standard') standardIds.add(h.id);
  }
  _profileMapCache = {
    minimal: minimalIds,
    standard: new Set([...minimalIds, ...standardIds]),
  };
  return _profileMapCache;
}

let _disabledHooksCache = null;

export function getDisabledHookIds() {
  if (_disabledHooksCache) return _disabledHooksCache;
  const raw = (process.env.ECC_DISABLED_HOOKS || '').trim();
  _disabledHooksCache = raw
    ? new Set(raw.split(',').map((v) => v.trim().toLowerCase()).filter(Boolean))
    : new Set();
  return _disabledHooksCache;
}

export function getActiveProfile() {
  const env = (process.env.ECC_HOOK_PROFILE || '').toLowerCase().trim();
  return VALID_PROFILES.has(env) ? env : 'standard';
}

export function isHookEnabled(hookId, options) {
  const disabled = getDisabledHookIds();
  if (disabled.has(hookId)) return false;
  const profile = options?.profile || getActiveProfile();
  const profileMap = buildProfileMap();
  const enabledSet = profileMap[profile];
  if (!enabledSet) return true;
  return enabledSet.has(hookId);
}

/** ecosystem-health-guard E14 compatibility — always valid since it is derived after Single SSOT */
export function validateProfileCoverage(registryHookIds, profileUncheckedIds = []) {
  const profileMap = buildProfileMap();
  // 2-tier (minimal ⊂ standard). standard is superset of all profiles (strict tier removed, 2026-06-11).
  const allProfileIds = profileMap.standard;
  const registrySet = new Set(registryHookIds);
  const uncheckedSet = new Set(profileUncheckedIds);
  const orphaned = [...allProfileIds].filter((id) => !registrySet.has(id));
  const missing = [...registrySet].filter(
    (id) => !allProfileIds.has(id) && !uncheckedSet.has(id),
  );
  return { valid: orphaned.length === 0 && missing.length === 0, orphaned, missing };
}

export function getEnabledHooks(profile) {
  const p = profile || getActiveProfile();
  const profileMap = buildProfileMap();
  const enabledSet = profileMap[p];
  if (!enabledSet) return [];
  const disabled = getDisabledHookIds();
  return [...enabledSet].filter((id) => !disabled.has(id)).sort();
}
